# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/sell.*, role: ROLE_USER }
        - { path: ^/organiser/approval.*, role: ROLE_USER }
        - { path: ^/organiser/locations, role: ROLE_USER }
        - { path: ^/organiser/location_approval, role: ROLE_USER }
        - { path: ^/business/offer, role: ROLE_USER }
        - { path: ^/business/approval.*, role: ROLE_USER }
        - { path: ^/business/business.*, role: ROLE_USER }
        - { path: ^/buy.*, role: ROLE_USER }
        - { path: ^/agorasmena.*, role: ROLE_USER }
        - { path: ^/poulimena.*, role: ROLE_USER }
        - { path: ^/vote.*, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
