prosfora:
    pattern: /offer
    defaults: { _controller: AcmeUserBundle:Business:index }
business_add:
    pattern: /add
    defaults: { _controller: AcmeUserBundle:Business:add }
business:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Epixeirhsh:index }
bapproval:
    pattern: /approval/{approval}
    defaults: { _controller: AcmeUserBundle:BusinessApproval:isApproved, approval:NULL  }
bok:
    pattern: /ok/{id}
    defaults: { _controller: AcmeUserBundle:BusinessApproval:ok }
bno:
    pattern: /no/{id}
    defaults: { _controller: AcmeUserBundle:BusinessApproval:no }
