locations:
    pattern: /locations
    defaults: { _controller: AcmeUserBundle:Locations:index }
locations_new:
    pattern: /locations_new
    defaults: { _controller: AcmeUserBundle:Locations:new }
diorganotis:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Organiser:index }
approval:
    pattern: /approval/{approval}
    defaults: { _controller: AcmeUserBundle:Approval:isApproved, approval:NULL  }
ok:
    pattern: /ok/{id}
    defaults: { _controller: AcmeUserBundle:Approval:ok }
no:
    pattern: /no/{id}
    defaults: { _controller: AcmeUserBundle:Approval:no }
