# src/Acme/UserBundle/Resources/config/routing.yml

home:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Pazari:index }
sell:
    pattern:  /sell/{id}
    defaults: { _controller: AcmeUserBundle:Sell:index }
sell_add:
    pattern: /sell_add
    defaults: { _controller: AcmeUserBundle:Sell:index }
buy:
    pattern:  /buy/{id}
    defaults: { _controller: AcmeUserBundle:Buy:index }
buy_new:
    pattern:  /buy_new/{location_id}/{offer_id}
    defaults: { _controller: AcmeUserBundle:Buy:new }
profile:
    pattern:  /profile
    defaults: { _controller: AcmeUserBundle:Profile:show}
edit:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeUserBundle:Poulimena:edit}
edit_new:
    pattern:  /edit_new
    defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
poulimena:
    pattern:  /poulimena
    defaults: { _controller: AcmeUserBundle:Poulimena:show}
agorasmena:
    pattern:  /agorasmena
    defaults: { _controller: AcmeUserBundle:Kalathi:show}
buy_delete:
    pattern:  /agorasmena/{id}
    defaults: { _controller: AcmeUserBundle:Kalathi:delete}
vote:
    pattern:  /vote/{name}
    defaults: { _controller: AcmeUserBundle:Vote:index}
sell_new:
    pattern:  /sell_new
    defaults: { _controller: AcmeUserBundle:Sell:new }
price:
    pattern:  /price
    defaults: { _controller: AcmeUserBundle:Price:new }
edit_new:
   pattern: /edit_new
   defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
edit_new_sell:
   pattern: /edit_new_sell
   defaults: { _controller: AcmeUserBundle:Poulimena:editnewsell}
vote:
   pattern: /vote
   defaults: { _controller: AcmeUserBundle:Vote:index}
admin:
    resource: "@AcmeUserBundle/Resources/config/routingadmin.yml"
    prefix:   /admin
pazari:
    pattern:  /pazari
    defaults: { _controller: AcmeUserBundle:Pazari:index }
ola:
    pattern:  /ola
    defaults: { _controller: AcmeUserBundle:Pazari:new }
laxanika:
    pattern:  /pazari?category=λαχανικά
    defaults: { _controller: AcmeUserBundle:Pazari:index}
opwrokhpeutika:
    pattern:  /pazari?category=οπωροκηπευτικά
    defaults: { _controller: AcmeUserBundle:Pazari:index }
frouta:
    pattern:  /pazari?category=φρούτα
    defaults: { _controller: AcmeUserBundle:Pazari:index }
ospria:
    pattern:  /pazari?category=όσπρια
    defaults: { _controller: AcmeUserBundle:Pazari:index }
ladi:
    pattern:  /pazari?category=λάδι
    defaults: { _controller: AcmeUserBundle:Pazari:index}
meli:
    pattern:  /pazari?category=μέλι
    defaults: { _controller: AcmeUserBundle:Pazari:index}
galaktokomika:
    pattern:  /pazari?category=γαλακτοκομικά
    defaults: { _controller: AcmeUserBundle:Pazari:index }
xorta:
    pattern:  /pazari?category=χόρτα
    defaults: { _controller: AcmeUserBundle:Pazari:index}
kreas:
    pattern:  /pazari?category=κρέας
    defaults: { _controller: AcmeUserBundle:Pazari:index }
8alassina:
    pattern:  /pazari?category=θαλασσινά
    defaults: { _controller: AcmeUserBundle:Pazari:index}
viologika:
    pattern:  /pazari?category=βιολογικά-προϊόντα
    defaults: { _controller: AcmeUserBundle:Pazari:index}
alla:
    pattern:  /pazari?category=άλλα
    defaults: { _controller: AcmeUserBundle:Pazari:index }
locations:
    pattern: /locations
    defaults: { _controller: AcmeUserBundle:Locations:index }
locations_new:
    pattern: /locations_new
    defaults: { _controller: AcmeUserBundle:Locations:new }
prosfores:
    pattern: /prosfores
    defaults: { _controller: AcmeUserBundle:Prosfores:index }
approval:
    pattern: /approval
    defaults: { _controller: AcmeUserBundle:Approval:index }
ok:
    pattern: /ok{id}
    defaults: { _controller: AcmeUserBundle:Approval:ok }
no:
    pattern: /no{id}
    defaults: { _controller: AcmeUserBundle:Approval:no }