# src/Acme/UserBundle/Resources/config/routing.yml

home:
    pattern: /
    defaults: { _controller: AcmeUserBundle:News:index }
events:
    pattern: /events
    defaults: { _controller: AcmeUserBundle:Events:index }
newsletter:
    pattern: /newsletter
    defaults: { _controller: AcmeUserBundle:Newsletter:index }
#sell:
#    pattern:  /sell/{id}
#    defaults: { _controller: AcmeUserBundle:Sell:index }
#sellbusiness:
#    pattern:  /sellbusiness/{id}
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
#sell_add:
#    pattern: /sell_add
#    defaults: { _controller: AcmeUserBundle:Sell:index }
#sellbusiness_add:
#    pattern: /sellbusiness_add
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
#user
buy:
    pattern:  /buy/{id}
    defaults: { _controller: AcmeUserBundle:Buy:index }
#user
buy_new:
    pattern:  /buy_new/{location_id}/{offer_id}
    defaults: { _controller: AcmeUserBundle:Buy:new }
#all
profile:
    pattern:  /profile
    defaults: { _controller: AcmeUserBundle:Profile:show}
#all
edit:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeUserBundle:Poulimena:edit}
#all
edit_new:
    pattern:  /edit_new
    defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
#all
about:
    pattern:  /about
    defaults: { _controller: AcmeUserBundle:About:new}
#farmer
#poulimena:
#    pattern:  /poulimena
#    defaults: { _controller: AcmeUserBundle:Poulimena:show}
#user
agorasmena:
    pattern:  /agorasmena
    defaults: { _controller: AcmeUserBundle:Kalathi:show}
buy_delete:
    pattern:  /agorasmena/{id}
    defaults: { _controller: AcmeUserBundle:Kalathi:delete}
#vote:
#    pattern:  /vote/{name}
#    defaults: { _controller: AcmeUserBundle:Vote:index}
#sell_new:
#    pattern:  /sell_new
#    defaults: { _controller: AcmeUserBundle:Sell:new }
#sellbusiness_new:
#    pattern:  /sellbusiness_new
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:new }
price:
    pattern:  /price
    defaults: { _controller: AcmeUserBundle:Price:new }
edit_new:
   pattern: /edit_new
   defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
edit_new_sell:
   pattern: /edit_new_sell
   defaults: { _controller: AcmeUserBundle:Poulimena:editnewsell}
#vote:
   #pattern: /vote
   #defaults: { _controller: AcmeUserBundle:Vote:index}




admin:
    resource: "@AcmeUserBundle/Resources/config/routingadmin.yml"
    prefix:   /admin
agrotis:
    resource: "@AcmeUserBundle/Resources/config/routing-agrotis.yml"
    prefix:   /agrotis
businessroute:
    resource: "@AcmeUserBundle/Resources/config/routing-business.yml"
    prefix:   /business
organiser:
    resource: "@AcmeUserBundle/Resources/config/routing-organiser.yml"
    prefix:   /organiser
volunteer:
    resource: "@AcmeUserBundle/Resources/config/routing-volunteer.yml"
    prefix:   /volunteer
votes:
    resource: "@AcmeUserBundle/Resources/config/routing-votes.yml"
    prefix: /votes



#user
ola:
    pattern:  /agora
    defaults: { _controller: AcmeUserBundle:Pazari:new }
#user
pazari:
    pattern:  /agora/{category}
    defaults: { _controller: AcmeUserBundle:Pazari:index, category:"all" }

