# src/Acme/UserBundle/Resources/config/routing.yml

home:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Pazari:index }
pazari:
    pattern:  /pazari
    defaults: { _controller: AcmeUserBundle:Pazari:index }
sell:
    pattern:  /sell/{id}
    defaults: { _controller: AcmeUserBundle:Sell:index }
sell_add:
    pattern: /sell_add
    defaults: { _controller: AcmeUserBundle:Sell:index }
buy:
    pattern:  /buy/{id}
    defaults: { _controller: AcmeUserBundle:Buy:index }
buy_new:
    pattern:  /buy_new
    defaults: { _controller: AcmeUserBundle:Buy:new }
profile:
    pattern:  /profile
    defaults: { _controller: AcmeUserBundle:Profile:show}
edit:
    pattern:  /edit{id}
    defaults: { _controller: AcmeUserBundle:Poulimena:edit}
edit_new:
    pattern:  /edit_new
    defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
poulimena:
    pattern:  /poulimena
    defaults: { _controller: AcmeUserBundle:Poulimena:show}
agorasmena:
    pattern:  /agorasmena
    defaults: { _controller: AcmeUserBundle:Kalathi:show}
buy_delete:
    pattern:  /agorasmena{id}
    defaults: { _controller: AcmeUserBundle:Kalathi:delete}
vote:
    pattern:  /vote{name}
    defaults: { _controller: AcmeUserBundle:Vote:index}
sell_new:
    pattern:  /sell_new
    defaults: { _controller: AcmeUserBundle:Sell:new }
price:
    pattern:  /price
    defaults: { _controller: AcmeUserBundle:Price:new }
edit_new:
   pattern: /edit_new
   defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
edit_new_sell:
   pattern: /edit_new_sell
   defaults: { _controller: AcmeUserBundle:Poulimena:editnewsell}
vote:
   pattern: /vote
   defaults: { _controller: AcmeUserBundle:Vote:index}
admin:
    resource: "@AcmeUserBundle/Resources/config/routingadmin.yml"
    prefix:   /admin
