
#agora:
#    patter: /agora
#    defaults: {_controller: AcmeUserBundle:PazariAgrotes:index}
sell:
    pattern:  /sell/{id}
    defaults: { _controller: AcmeUserBundle:Sell:index }
sellbusiness:
    pattern:  /sellbusiness/{id}
    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
sell_add:
    pattern: /sell_add
    defaults: { _controller: AcmeUserBundle:Sell:index }
sellbusiness_add:
    pattern: /sellbusiness_add
    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
sell_new:
    pattern:  /sell_new
    defaults: { _controller: AcmeUserBundle:Sell:new }
sellbusiness_new:
    pattern:  /sellbusiness_new
    defaults: { _controller: AcmeUserBundle:Sellbusiness:new }
poulimena:
    pattern:  /poulimena
    defaults: { _controller: AcmeUserBundle:Poulimena:show}
agrotis:
    pattern:  /agrotis
    defaults: { _controller: AcmeUserBundle:Agrotis:index}
prosfores:
    pattern: /prosfores
    defaults: { _controller: AcmeUserBundle:Prosfores:index }
businessoffer:
    pattern: /businessoffer
    defaults: { _controller: AcmeUserBundle:Businessprosfores:index }