
admin:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Admin:index }

admin_products:
    pattern: /products
    defaults: { _controller: AcmeUserBundle:AdminProducts:index }

admin_product_new:
    pattern: /products_new
    defaults: { _controller: AcmeUserBundle:AdminProducts:upload }
admin_product_delete:
    pattern: /products_delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminProducts:delete }

admin_locations:
    pattern: /locations
    defaults: { _controller: AcmeUserBundle:AdminLocations:index }
admin_locations_edit:
    pattern: /locations/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminLocations:edit }
admin_locations_new:
    pattern: /locations/new
    defaults: { _controller: AcmeUserBundle:AdminLocations:new }
admin_locations_delete:
    pattern: /locations/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminLocations:delete }

#admin_locations_new:
#    pattern: /locations_new
#    defaults: { _controller: AcmeUserBundle:AdminLocations:new }
