# src/Acme/UserBundle/Resources/config/routing.yml

home:
    pattern: /
    defaults: { _controller: AcmeUserBundle:News:index }
#sell:
#    pattern:  /sell/{id}
#    defaults: { _controller: AcmeUserBundle:Sell:index }
#sellbusiness:
#    pattern:  /sellbusiness/{id}
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
#sell_add:
#    pattern: /sell_add
#    defaults: { _controller: AcmeUserBundle:Sell:index }
#sellbusiness_add:
#    pattern: /sellbusiness_add
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:index }
#user
buy:
    pattern:  /buy/{id}
    defaults: { _controller: AcmeUserBundle:Buy:index }
#user
buy_new:
    pattern:  /buy_new/{location_id}/{offer_id}
    defaults: { _controller: AcmeUserBundle:Buy:new }
#all
profile:
    pattern:  /profile
    defaults: { _controller: AcmeUserBundle:Profile:show}
#all
edit:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeUserBundle:Poulimena:edit}
#all
edit_new:
    pattern:  /edit_new
    defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
#farmer
#poulimena:
#    pattern:  /poulimena
#    defaults: { _controller: AcmeUserBundle:Poulimena:show}
#user
agorasmena:
    pattern:  /agorasmena
    defaults: { _controller: AcmeUserBundle:Kalathi:show}
buy_delete:
    pattern:  /agorasmena/{id}
    defaults: { _controller: AcmeUserBundle:Kalathi:delete}
vote:
    pattern:  /vote/{name}
    defaults: { _controller: AcmeUserBundle:Vote:index}
#sell_new:
#    pattern:  /sell_new
#    defaults: { _controller: AcmeUserBundle:Sell:new }
#sellbusiness_new:
#    pattern:  /sellbusiness_new
#    defaults: { _controller: AcmeUserBundle:Sellbusiness:new }
price:
    pattern:  /price
    defaults: { _controller: AcmeUserBundle:Price:new }
edit_new:
   pattern: /edit_new
   defaults: { _controller: AcmeUserBundle:Poulimena:editnew}
edit_new_sell:
   pattern: /edit_new_sell
   defaults: { _controller: AcmeUserBundle:Poulimena:editnewsell}
vote:
   pattern: /vote
   defaults: { _controller: AcmeUserBundle:Vote:index}




admin:
    resource: "@AcmeUserBundle/Resources/config/routingadmin.yml"
    prefix:   /admin
agrotis:
    resource: "@AcmeUserBundle/Resources/config/routing-agrotis.yml"
    prefix:   /agrotis
businessroute:
    resource: "@AcmeUserBundle/Resources/config/routing-business.yml"
    prefix:   /business
organiser:
    resource: "@AcmeUserBundle/Resources/config/routing-organiser.yml"
    prefix:   /organiser



#user
ola:
    pattern:  /agora
    defaults: { _controller: AcmeUserBundle:Pazari:new }
#user
pazari:
    pattern:  /agora/{category}
    defaults: { _controller: AcmeUserBundle:Pazari:index, category:"all" }
#locations:
#    pattern: /locations
#    defaults: { _controller: AcmeUserBundle:Locations:index }
#locations_new:
#    pattern: /locations_new
#    defaults: { _controller: AcmeUserBundle:Locations:new }
prosfores:
    pattern: /prosfores
    defaults: { _controller: AcmeUserBundle:Prosfores:index }
approval:
    pattern: /approval
    defaults: { _controller: AcmeUserBundle:Approval:index }
ok:
    pattern: /ok{id}
    defaults: { _controller: AcmeUserBundle:Approval:ok }
no:
    pattern: /no{id}
    defaults: { _controller: AcmeUserBundle:Approval:no }

#business:
#    pattern: /business
#    defaults: { _controller: AcmeUserBundle:Business:index }
#business_add:
#    pattern: /business_add
#    defaults: { _controller: AcmeUserBundle:Business:add }
#businessprosfores:
#    pattern: /businessprosfores
#    defaults: { _controller: AcmeUserBundle:Businessprosfores:index }
#about:
#    pattern: /about
#    defaults: { _controller: AcmeUserBundle:About:new }
