# src/Acme/UserBundle/Resources/config/routing.yml

home:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Pazari:index }
pazari:
    pattern:  /pazari
    defaults: { _controller: AcmeUserBundle:Pazari:index }
sell:
    pattern:  /sell
    defaults: { _controller: AcmeUserBundle:Sell:index }
sell_add:
    pattern: /sell_add
    defaults: { _controller: AcmeUserBundle:Sell:index }
buy:
    pattern:  /buy
    defaults: { _controller: AcmeUserBundle:Buy:index }
buy_new:
    pattern:  /buy_new
    defaults: { _controller: AcmeUserBundle:Buy:new }
profile:
    pattern:  /profile
    defaults: { _controller: AcmeUserBundle:Profile:show}
sell_new:
    pattern:  /sell_new
    defaults: { _controller: AcmeUserBundle:Sell:new }
price:
    pattern:  /price
    defaults: { _controller: AcmeUserBundle:Price:new }
edit_new:
   pattern: /edit_new
   defaults: { _controller: AcmeUserBundle:Profile:editnew}
edit_new_sell:
   pattern: /edit_new_sell
   defaults: { _controller: AcmeUserBundle:Profile:editnewsell}

admin:
    resource: "@AcmeUserBundle/Resources/config/routingadmin.yml"
    prefix:   /admin
