locations:
    pattern: /locations
    defaults: { _controller: AcmeUserBundle:Locations:index }
locations_new:
    pattern: /locations_new
    defaults: { _controller: AcmeUserBundle:Locations:new }
