
admin:
    pattern: /
    defaults: { _controller: AcmeUserBundle:Admin:index }

admin_products:
    pattern: /products
    defaults: { _controller: AcmeUserBundle:AdminProducts:index }

admin_product_new:
    pattern: /products_new
    defaults: { _controller: AcmeUserBundle:AdminProducts:upload }
admin_product_delete:
    pattern: /products_delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminProducts:delete }

admin_locations:
    pattern: /locations
    defaults: { _controller: AcmeUserBundle:AdminLocations:index }
admin_locations_edit:
    pattern: /locations/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminLocations:edit }
admin_locations_new:
    pattern: /locations/new
    defaults: { _controller: AcmeUserBundle:AdminLocations:new }
admin_locations_delete:
    pattern: /locations/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminLocations:delete }


admin_b2b:
    pattern: /b2b
    defaults: { _controller: AcmeUserBundle:AdminBusiness:index }
admin_b2b_edit:
    pattern: /b2b/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminBusiness:edit }
admin_b2b_new:
    pattern: /b2b/new
    defaults: { _controller: AcmeUserBundle:AdminBusiness:new }
admin_b2b_delete:
    pattern: /b2b/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminBusiness:delete }



admin_news:
    pattern: /news
    defaults: { _controller: AcmeUserBundle:AdminNews:index }
admin_news_edit:
    pattern: /news/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminNews:edit }
admin_news_new:
    pattern: /news/new
    defaults: { _controller: AcmeUserBundle:AdminNews:new }
admin_news_delete:
    pattern: /news/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminNews:delete }

admin_events:
    pattern: /events
    defaults: { _controller: AcmeUserBundle:AdminEvents:index }
admin_events_edit:
    pattern: /events/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminEvents:edit }
admin_events_new:
    pattern: /events/new
    defaults: { _controller: AcmeUserBundle:AdminEvents:new }
admin_events_delete:
    pattern: /events/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminEvents:delete }

admin_volunteer:
    pattern: /volunteer
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:index }
admin_volunteer_edit:
    pattern: /volunteer/edit/{id}
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:edit }
admin_volunteer_new:
    pattern: /volunteer/new
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:new }
admin_volunteer_delete:
    pattern: /volunteer/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:delete }
admin_volunteer_echo:
    pattern: /volunteer/echo
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:echo }
admin_volunteer_echo_delete:
    pattern: /volunteer/echo/delete/{id}
    defaults: { _controller: AcmeUserBundle:AdminVolunteer:echodelete }
#admin_locations_new:
#    pattern: /locations_new
#    defaults: { _controller: AcmeUserBundle:AdminLocations:new }
